### ISSUE TITLE
regarding the .me website

### ISSUE THREAD

**Issue by rahulkumaran** [vchrombie/vchrombie.github.io#2]
This is not an issue! Just wanted to know something actually.
How did you link the .github.io website to a .me website? Did you buy a .me domain or did you get a free one on github's student pack? if you got a free one, could you tell me how to utilise it? :smile:

thanks!

**Comment by vchrombie** [comment]
Yes @rahulkumaran 
I got it from the github's student pack.

I you have a domain with you, just go to **Settings** of the repository.
Slide down to **Github pages** 
Enter your domain in the **Custom Domain** and wait for some time to get it updated.

Feel free to contact me if you need help :)
