### ISSUE TITLE
adding topic #portfolio-websites

### ISSUE THREAD

**Issue by umihico** [vchrombie/vchrombie.github.io#3]
Hello! I'm collecting screenshots of everybody's portfolio here.
https://umihico.github.io/thumbnailed-portfolio-websites/
If you don't mind, I'd like you to add topic #portfolio-website. Then I can crawl your cool portfolio next time. Thank you!

**Comment by vchrombie** [comment]
Sorry, I never kept an eye on the issue tracker here. Sure, will do that.
