### ISSUE TITLE
Restrict the Tags and Categories to open in the same tab

### ISSUE THREAD

**Issue by vchrombie** [vchrombie/vchrombie.github.io#3]
Currently, when you click on any tag in [Tags](https://vchrombie.github.io/blog/tags) or category in [Categories](https://vchrombie.github.io/blog/categories), they open in a new window. 

I tried this but still of no use. Couldn't figure out the problem.
```
<a target="_self" 
```

I need them just to scroll to the particular `id` in the same page.

**Comment by vinopaldimit** [comment]
I would like to take this issue.

**Comment by vchrombie** [comment]
@vinopaldimit yes, please. :slightly_smiling_face:

**Comment by vchrombie** [comment]
@vinopaldimit, any help needed ?

**Comment by vinopaldimit** [comment]
@vchrombie sorry, didn't see your reply until now. looking at it now.

**Comment by vchrombie** [comment]
@vinopaldimit, it is fine, take your time.

**Comment by vchrombie** [comment]
@vinopaldimit, thanks for the effort. I fixed this with a hack temporarily. :slightly_smiling_face: 
Closing this as it is no much existing.
